from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, computed_field, model_validator


def to_camel(value: str) -> str:
    parts = value.split("_")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


class CamelModel(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_camel,
        from_attributes=True,
        populate_by_name=True,
    )


JsonDict = dict[str, Any]
Vec3 = tuple[float, float, float]


def _accept_legacy_keys(data: Any, renames: tuple[tuple[str, str], ...]) -> Any:
    """Backward-compat translator for Phase 5 kindParams renames. If
    `data` is a dict, every (old → new) pair is applied: when `old` is
    present and `new` is not, `data[new]` is set to `data[old]` and `old`
    is dropped. When both are present, `old` is silently discarded so the
    new value wins.

    Used inside `model_validator(mode="before")` on each kind-params
    Pydantic class that participates in the unification.
    """
    if not isinstance(data, dict):
        return data
    out = dict(data)
    for old, new in renames:
        if old in out:
            if new not in out:
                out[new] = out.pop(old)
            else:
                out.pop(old, None)
    return out


class Vec3Mm(CamelModel):
    """A position vector in millimetres. Frame is implied by the
    surrounding field name (e.g. `position_mm_body_local`).
    """

    x: float
    y: float
    z: float


# Whitelist of anchor IDs the system understands. Anything outside this
# set should be rejected at validation. Keep in sync with assembly_solver
# and beamPlacement.ts.
AssetAnchorId = Literal[
    # Standard box-face anchors (generated by assembly_solver.standard_anchor)
    "+x",
    "-x",
    "+y",
    "-y",
    "+z",
    "-z",
    "center",
    # Optical-element anchors
    "optical_anchor",
    "in",
    "intercept_in",
    "intercept_out",
    "intercept_face",
    "seed",
    "out",
    # AOM-specific direction anchor (Phase 8 refactor 2026-05-10).
    # `id="rf_direction"` carries the RF / acoustic propagation direction
    # in body-local frame via `directionBodyLocal`; position is body
    # origin and apertureMm is unused for this anchor.
    "rf_direction",
]


class AssetAnchor(CamelModel):
    """A point of interest on a 3D asset, in body-local (Z-up) frame.

    Phase 4 of the schema unification (2026-05-07): formalises the
    previously raw-JSONB anchor blob into a typed Pydantic model. The
    new field names embed frame and unit so a future reader cannot
    misinterpret coordinates:

      position_mm_body_local : {x, y, z} in mm, body-local Z-up frame
      direction_body_local   : {x, y, z} unit vector, body-local frame
                               (only present on face / optical anchors)
      aperture_mm            : optional clear-aperture diameter in mm

    Backward compatibility: input deserialisation accepts the legacy
    field names (`localPosition`, `localDirection`) so a client/migration
    that hasn't been updated yet still validates. All new writes emit the
    new names. The alembic migration `0018_normalize_asset_anchors`
    rewrites every existing JSONB blob to the new shape.
    """

    id: AssetAnchorId
    position_mm_body_local: Vec3Mm = Field(
        ...,
        validation_alias="positionMmBodyLocal",
        serialization_alias="positionMmBodyLocal",
    )
    direction_body_local: Vec3Mm | None = Field(
        default=None,
        validation_alias="directionBodyLocal",
        serialization_alias="directionBodyLocal",
    )
    aperture_mm: float | None = None
    # Rectangular aperture (e.g. PBS / BS cube diagonal cement plane is
    # a rectangle, not a square). When both width + height are set the
    # editor + ray-tracer use them; when missing we fall back to
    # 2*aperture_mm x 2*aperture_mm. Independent of aperture_mm so an
    # anchor can carry both shapes simultaneously without ambiguity.
    aperture_width_mm: float | None = None
    aperture_height_mm: float | None = None
    name: str | None = None
    type: str | None = None

    @model_validator(mode="before")
    @classmethod
    def _accept_legacy_field_names(cls, data: Any) -> Any:
        """Accept legacy `localPosition` / `localDirection` keys on
        input. The migration rewrites stored data, but client code or
        external imports that still send the old names should round-trip
        cleanly until they're updated. Output is always the new names.
        """
        if not isinstance(data, dict):
            return data
        out = dict(data)
        if "localPosition" in out and "positionMmBodyLocal" not in out and "position_mm_body_local" not in out:
            out["positionMmBodyLocal"] = out.pop("localPosition")
        else:
            out.pop("localPosition", None)
        if "localDirection" in out and "directionBodyLocal" not in out and "direction_body_local" not in out:
            out["directionBodyLocal"] = out.pop("localDirection")
        else:
            out.pop("localDirection", None)
        return out


class Asset3DBase(CamelModel):
    name: str
    asset_type: str
    file_path: str
    source: str | None = None
    source_url: str | None = None
    unit: Literal["mm", "m"] = "mm"
    scale_factor: float = 1.0
    anchors: list[AssetAnchor] = Field(default_factory=list)


class Asset3DCreate(Asset3DBase):
    pass


class Asset3DUpdate(CamelModel):
    name: str | None = None
    asset_type: str | None = None
    file_path: str | None = None
    source: str | None = None
    source_url: str | None = None
    unit: Literal["mm", "m"] | None = None
    scale_factor: float | None = None
    anchors: list[AssetAnchor] | None = None


class LocalAssetImport(CamelModel):
    source_path: str
    name: str | None = None
    component_type: str = "custom_3d"
    brand: str | None = None
    model: str | None = None
    unit: Literal["mm", "m"] = "mm"
    scale_factor: float = 1.0


class Asset3DOut(Asset3DBase):
    id: uuid.UUID
    created_at: datetime


PhysicsCapability = Literal["stress", "optical", "rf", "em", "thermal", "fluid", "quantum"]


class ComponentBase(CamelModel):
    name: str
    component_type: str
    brand: str | None = None
    model: str | None = None
    # serial_number relocated to SceneObject in alembic 0015 (per-physical-unit).
    asset_3d_id: uuid.UUID | None = None
    properties: JsonDict = Field(default_factory=dict)
    physics_capabilities: list[PhysicsCapability] = Field(default_factory=list)
    notes: str | None = None


class ComponentCreate(ComponentBase):
    pass


class ComponentUpdate(CamelModel):
    name: str | None = None
    component_type: str | None = None
    brand: str | None = None
    model: str | None = None
    asset_3d_id: uuid.UUID | None = None
    properties: JsonDict | None = None
    physics_capabilities: list[PhysicsCapability] | None = None
    notes: str | None = None


class ComponentOut(ComponentBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    archived_at: datetime | None = None

    @computed_field(alias="componentName")
    @property
    def component_name(self) -> str:
        return self.name


class SceneObjectBase(CamelModel):
    name: str | None = None
    x_mm: float = 0
    y_mm: float = 0
    z_mm: float = 0
    rx_deg: float = 0
    ry_deg: float = 0
    rz_deg: float = 0
    visible: bool = True
    locked: bool = False
    serial_number: str | None = None
    properties: JsonDict = Field(default_factory=dict)


class SceneObjectCreate(SceneObjectBase):
    component_id: uuid.UUID
    collection_id: uuid.UUID | None = None


class SceneObjectUpdate(CamelModel):
    name: str | None = None
    x_mm: float | None = None
    y_mm: float | None = None
    z_mm: float | None = None
    rx_deg: float | None = None
    ry_deg: float | None = None
    rz_deg: float | None = None
    visible: bool | None = None
    locked: bool | None = None
    serial_number: str | None = None
    properties: JsonDict | None = None


class SceneObjectOut(SceneObjectBase):
    id: uuid.UUID
    component_id: uuid.UUID
    name: str
    updated_at: datetime


class ConnectionBase(CamelModel):
    connection_type: str
    from_object_id: uuid.UUID
    from_port: str | None = None
    to_object_id: uuid.UUID
    to_port: str | None = None
    label: str | None = None
    properties: JsonDict = Field(default_factory=dict)


class ConnectionCreate(ConnectionBase):
    pass


class ConnectionUpdate(CamelModel):
    connection_type: str | None = None
    from_object_id: uuid.UUID | None = None
    from_port: str | None = None
    to_object_id: uuid.UUID | None = None
    to_port: str | None = None
    label: str | None = None
    properties: JsonDict | None = None


class ConnectionOut(ConnectionBase):
    id: uuid.UUID
    created_at: datetime


RelationType = Literal[
    "same_position",
    "offset_position",
    "distance",
    "same_direction",
    "opposite_direction",
    "perpendicular_direction",
    "look_at",
    "face_touch",
    "face_parallel",
    "face_offset",
    "face_align_center",
    "face_distance",
    "coincident",
    "parallel",
    "perpendicular",
    "concentric",
    "tangent",
    "angle",
    "lock_transform",
    "align_axis",
]


def selector_normal(selector: JsonDict) -> tuple[float, float, float] | None:
    value = selector.get("normal") or selector.get("localDirection")
    if isinstance(value, dict):
        value = (value.get("x"), value.get("y"), value.get("z"))
    if not isinstance(value, (list, tuple)) or len(value) != 3:
        return None
    if not all(isinstance(item, (int, float)) for item in value):
        return None
    vector = tuple(float(item) for item in value)
    length = sum(item * item for item in vector) ** 0.5
    if length == 0:
        return None
    return vector


def normals_dot(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    len_a = sum(item * item for item in a) ** 0.5
    len_b = sum(item * item for item in b) ** 0.5
    return sum(left * right for left, right in zip(a, b, strict=True)) / (len_a * len_b)


class AssemblyRelationBase(CamelModel):
    name: str
    relation_type: RelationType
    object_a_id: uuid.UUID
    object_b_id: uuid.UUID
    selector_a: JsonDict = Field(default_factory=dict)
    selector_b: JsonDict = Field(default_factory=dict)
    offset_mm: float | None = None
    angle_deg: float | None = None
    tolerance_mm: float = 0.01
    enabled: bool = True
    solved: bool = False
    properties: JsonDict = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_relation_geometry(self) -> "AssemblyRelationBase":
        if self.object_a_id == self.object_b_id:
            raise ValueError("A relation must reference two different objects.")
        normal_a = selector_normal(self.selector_a)
        normal_b = selector_normal(self.selector_b)
        relation_type = {
            "face_distance": "face_offset",
            "coincident": "face_touch",
            "parallel": "face_parallel",
            "perpendicular": "perpendicular_direction",
            "align_axis": "same_direction",
        }.get(self.relation_type, self.relation_type)
        # Direction relations: solver actively rotates the driven object so the
        # *local* selector normals do not need to be pre-aligned. We only insist
        # they exist (non-zero) so the solver has something to align.
        if relation_type in {
            "same_direction",
            "face_parallel",
            "opposite_direction",
            "perpendicular_direction",
            "look_at",
        }:
            if normal_a is None or normal_b is None:
                raise ValueError(
                    f"Relation '{relation_type}' requires both anchors to declare a non-zero normal/localDirection.",
                )
        if relation_type in {"offset_position", "face_offset"} and self.offset_mm is None:
            params = self.properties.get("params")
            has_vector_offset = isinstance(params, dict) and isinstance(params.get("offset"), dict)
            if not has_vector_offset:
                raise ValueError("Offset relations require offsetMm or params.offset.")
        if relation_type == "distance" and self.offset_mm is None:
            params = self.properties.get("params")
            has_distance = isinstance(params, dict) and isinstance(params.get("distance"), (int, float))
            if not has_distance:
                raise ValueError("Distance relations require offsetMm or params.distance.")
        return self


class AssemblyRelationCreate(AssemblyRelationBase):
    pass


class AssemblyRelationUpdate(CamelModel):
    name: str | None = None
    relation_type: RelationType | None = None
    object_a_id: uuid.UUID | None = None
    object_b_id: uuid.UUID | None = None
    selector_a: JsonDict | None = None
    selector_b: JsonDict | None = None
    offset_mm: float | None = None
    angle_deg: float | None = None
    tolerance_mm: float | None = None
    enabled: bool | None = None
    solved: bool | None = None
    properties: JsonDict | None = None


class AssemblyRelationOut(AssemblyRelationBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class BeamPathBase(CamelModel):
    name: str
    wavelength_nm: float | None = None
    color: str = "#ff0000"
    source_object_id: uuid.UUID | None = None
    target_object_id: uuid.UUID | None = None
    points: list[Vec3] = Field(default_factory=list)
    properties: JsonDict = Field(default_factory=dict)
    visible: bool = True


class BeamPathCreate(BeamPathBase):
    pass


class BeamPathUpdate(CamelModel):
    name: str | None = None
    wavelength_nm: float | None = None
    color: str | None = None
    source_object_id: uuid.UUID | None = None
    target_object_id: uuid.UUID | None = None
    points: list[Vec3] | None = None
    properties: JsonDict | None = None
    visible: bool | None = None


class BeamPathOut(BeamPathBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class DeviceStateUpdate(CamelModel):
    state: JsonDict = Field(default_factory=dict)


class DeviceStateOut(CamelModel):
    object_id: uuid.UUID
    state: JsonDict = Field(default_factory=dict)
    updated_at: datetime


# =============================================================================
# Optical domain schemas
# =============================================================================

# --- Reusable building blocks ------------------------------------------------


class JonesVector(CamelModel):
    """Polarization state: complex 2-vector [Ex, Ey]."""

    ex_re: float = 1.0
    ex_im: float = 0.0
    ey_re: float = 0.0
    ey_im: float = 0.0


class GaussianMode(CamelModel):
    """Astigmatic Gaussian beam parameters along one transverse axis (x or y)."""

    waist_um: float = Field(gt=0)
    waist_z_offset_mm: float = 0.0
    m_squared: float = Field(default=1.0, ge=1.0)


TransverseModeKind = Literal["TEM00", "TEM_mn", "LG_pl", "multimode"]


class TransverseMode(CamelModel):
    kind: TransverseModeKind = "TEM00"
    indices_m: int | None = None
    indices_n: int | None = None
    indices_p: int | None = None
    indices_l: int | None = None

    @model_validator(mode="after")
    def check_indices(self) -> "TransverseMode":
        if self.kind == "TEM_mn":
            if self.indices_m is None or self.indices_n is None:
                raise ValueError("TEM_mn requires indices m and n.")
        elif self.kind == "LG_pl":
            if self.indices_p is None or self.indices_l is None:
                raise ValueError("LG_pl requires indices p and l.")
        return self


SpectrumLineshape = Literal["gaussian", "lorentzian", "voigt", "delta"]
SpectrumComponentKind = Literal["main", "sideband", "ase", "custom"]


class SpectrumComponent(CamelModel):
    kind: SpectrumComponentKind = "main"
    lineshape: SpectrumLineshape
    offset_mhz: float = 0.0
    fwhm_mhz: float | None = None
    voigt_gaussian_fwhm_mhz: float | None = None
    voigt_lorentzian_fwhm_mhz: float | None = None
    amplitude: float = Field(default=1.0, ge=0.0)

    @model_validator(mode="after")
    def check_lineshape_params(self) -> "SpectrumComponent":
        if self.lineshape == "delta":
            if self.fwhm_mhz is not None and self.fwhm_mhz != 0:
                raise ValueError("delta lineshape must not specify fwhm_mhz.")
        elif self.lineshape in {"gaussian", "lorentzian"}:
            if self.fwhm_mhz is None or self.fwhm_mhz <= 0:
                raise ValueError(f"{self.lineshape} lineshape requires positive fwhm_mhz.")
        elif self.lineshape == "voigt":
            if self.voigt_gaussian_fwhm_mhz is None or self.voigt_lorentzian_fwhm_mhz is None:
                raise ValueError("voigt lineshape requires voigt_gaussian_fwhm_mhz and voigt_lorentzian_fwhm_mhz.")
            if self.voigt_gaussian_fwhm_mhz <= 0 or self.voigt_lorentzian_fwhm_mhz <= 0:
                raise ValueError("voigt fwhm components must be positive.")
        return self


class Spectrum(CamelModel):
    center_thz: float = Field(gt=0)
    components: list[SpectrumComponent] = Field(default_factory=list)


# --- Time-domain envelopes ---------------------------------------------------
#
# These are the per-physics-module time representations used by the new
# transient solver. See docs/PHYSICS_TIME_DESIGN.md for the rationale on why
# we use slowly-varying envelopes instead of carrier-resolved fields.


class PulseEnvelope(CamelModel):
    """Slowly-varying complex envelope of an optical field, two polarisations.

    Stored on a uniform grid `t = t0_ns + (dt_ps/1000)·n`, n = 0..n_samples-1.
    Each sample is the complex amplitude in √mW units, so |E|² is instantaneous
    power. The envelope is in the rotating frame of `carrier_thz`; the full
    field is `Re[E(t) · exp(-i·2π·carrier·t)]` for each polarisation.

    For continuous-wave (CW) beams set `is_cw=True` — the envelope collapses
    to a single complex amplitude per polarisation and `dt_ps`/`n_samples`
    are ignored (length-1 sample arrays still hold the constant value).
    """
    is_cw: bool = True
    t0_ns: float = 0.0
    dt_ps: float = Field(default=0.0, ge=0.0)
    n_samples: int = Field(default=1, ge=1)
    carrier_thz: float = Field(gt=0)
    e_x_re: list[float] = Field(default_factory=list)
    e_x_im: list[float] = Field(default_factory=list)
    e_y_re: list[float] = Field(default_factory=list)
    e_y_im: list[float] = Field(default_factory=list)

    @model_validator(mode="after")
    def check_array_lengths(self) -> "PulseEnvelope":
        n = self.n_samples
        for name, arr in (
            ("e_x_re", self.e_x_re),
            ("e_x_im", self.e_x_im),
            ("e_y_re", self.e_y_re),
            ("e_y_im", self.e_y_im),
        ):
            if len(arr) not in (0, n):
                raise ValueError(f"{name} length {len(arr)} != n_samples {n}")
        if not self.is_cw and self.dt_ps <= 0:
            raise ValueError("Non-CW pulse must have dt_ps > 0")
        return self


class RFSignal(CamelModel):
    """Slowly-varying RF signal envelope on a uniform time grid.

    For digital trigger channels use `carrier_hz=0` and `amplitude` ∈ {0, 1}.
    For analog modulation, `amplitude` is √W (so amp² is instantaneous power)
    and `phase_rad` is referenced to `carrier_hz`.
    """
    is_cw: bool = True
    t0_ns: float = 0.0
    dt_ns: float = Field(default=0.0, ge=0.0)
    n_samples: int = Field(default=1, ge=1)
    carrier_hz: float = 0.0
    amplitude: list[float] = Field(default_factory=list)
    phase_rad: list[float] = Field(default_factory=list)

    @model_validator(mode="after")
    def check_array_lengths(self) -> "RFSignal":
        if len(self.amplitude) not in (0, self.n_samples):
            raise ValueError("amplitude length must match n_samples")
        if len(self.phase_rad) not in (0, self.n_samples):
            raise ValueError("phase_rad length must match n_samples")
        if not self.is_cw and self.dt_ns <= 0:
            raise ValueError("Non-CW RF signal must have dt_ns > 0")
        return self


class ScalarTrace(CamelModel):
    """Generic time-series for thermal / vacuum / DC current / voltage."""
    t_ns: list[float] = Field(default_factory=list)
    values: list[float] = Field(default_factory=list)
    unit: str = ""

    @model_validator(mode="after")
    def check_lengths(self) -> "ScalarTrace":
        if len(self.t_ns) != len(self.values):
            raise ValueError("t_ns and values must be the same length")
        return self


class QuantumTrace(CamelModel):
    """Density matrix ρ(t) for a small Hilbert space (typical N ≤ 64).

    `rho_real` and `rho_imag` are M × N × N nested lists where M = len(t_ns).
    Hermiticity is not enforced by the schema (solver responsibility).
    """
    t_ns: list[float] = Field(default_factory=list)
    rho_real: list[list[list[float]]] = Field(default_factory=list)
    rho_imag: list[list[list[float]]] = Field(default_factory=list)
    basis_labels: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def check_shapes(self) -> "QuantumTrace":
        m = len(self.t_ns)
        if len(self.rho_real) != m or len(self.rho_imag) != m:
            raise ValueError("rho arrays must have length len(t_ns)")
        if m == 0:
            return self
        n = len(self.basis_labels) if self.basis_labels else len(self.rho_real[0])
        for matrix in self.rho_real + self.rho_imag:
            if len(matrix) != n or any(len(row) != n for row in matrix):
                raise ValueError(f"rho matrices must be {n}×{n}")
        return self


# --- Port declarations -------------------------------------------------------


# "bidirectional" added so fiber endpoints (and future devices like
# circulators / 2-way switches) can declare a single port that both
# accepts and emits light. The optical solver / link checker treats
# bidirectional as compatible with any role on the matching side.
PortRole = Literal["input", "output", "bidirectional"]


class OpticalPort(CamelModel):
    port_id: str
    role: PortRole
    label: str | None = None
    kind: str | None = None  # "main", "reflected", "diffracted_plus", etc.


# --- Element kinds and their typed params ------------------------------------


ElementKind = Literal[
    "laser_source",
    "tapered_amplifier",
    "mirror",
    "lens_biconvex",        # V2 Phase 5 (alembic 0031): renamed from lens_spherical.
    "lens_plano_convex",    # V2 Phase 5: new kind for one-flat-one-curved lenses.
    "lens_cylindrical",
    "waveplate",
    "polarizer",
    "beam_splitter",
    "dichroic_mirror",
    "fiber_coupler",
    "fiber",
    "isolator",
    "aom",
    "eom",
    "nonlinear_crystal",
    "saturable_absorber",
    "detector",
    "camera",
    "spectrometer",
    "wavemeter",
    "beam_dump",
    "rf_source",            # Phase RF.1: DDS / synth / arbitrary waveform generator.
    "horn_antenna",         # Phase RF.7: microwave horn / antenna (radiates the RF chain output).
]


# Emitters ---------------------------------------------------------------------


class LaserSourceParams(CamelModel):
    """V2 Phase 3 (alembic 0029): all beam-defining fields moved to
    ``objects.properties.opticalSources[].beam``. The remaining knobs are
    advanced (noise) parameters that the V2 source does not yet model.

    Solver code reads beam state via ``v2_bindings.legacy_laser_kind_params_from_beam``
    instead of from this model; this class only validates the residual
    advanced fields and silently drops V1 inputs that still try to set
    centerWavelengthNm/nominalPowerMw/spectrum/spatialModeX/Y/transverseMode/polarization.
    """

    rin_dbc_per_hz: float | None = None
    frequency_noise_hz_per_sqrt_hz: float | None = None

    @model_validator(mode="before")
    @classmethod
    def _drop_v2_tracked_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            data = dict(data)
            for key in (
                "centerWavelengthNm",
                "center_wavelength_nm",
                "nominalPowerMw",
                "nominal_power_mw",
                "spectrum",
                "spatialModeX",
                "spatial_mode_x",
                "spatialModeY",
                "spatial_mode_y",
                "transverseMode",
                "transverse_mode",
                "polarization",
            ):
                data.pop(key, None)
        return data


class TaperedAmplifierAse(CamelModel):
    power_mw: float = Field(ge=0)
    bandwidth_nm: float = Field(gt=0)
    center_offset_nm: float = 0.0


class TaperedAmplifierAseSample(CamelModel):
    """ASE-only emission (no seed) at a given drive current.

    A real TA chip emits broadband ASE in BOTH directions when no seed is
    present — forward (out of the output port) and backward (out of the input
    port). The two powers don't have a fixed ratio; they depend on facet
    coatings and chip design. Sampling at a few representative currents lets
    the ray-tracer interpolate to the user's chosen drive current. We allow
    `drive_current_ma == 0` (TA off / threshold anchor; both powers ≈ 0),
    which is why this is `ge` not `gt`.
    """
    drive_current_ma: float = Field(ge=0)
    forward_power_mw: float = Field(ge=0)
    backward_power_mw: float = Field(ge=0)


class TaperedAmplifierGainSample(CamelModel):
    """Output power at a given (input_power, drive_current) operating point.

    With a seed present the ASE is partly suppressed (the gain medium is being
    extracted by the seed), so the backward power typically DROPS as input
    power rises while forward power saturates near the chip's saturation
    output. Sampling on a 2D grid (input × current) lets the ray-tracer
    bilinearly interpolate to live operating conditions. `drive_current_ma`
    is `ge=0` so the off-state can be anchored, matching the ASE table.
    """
    input_power_mw: float = Field(ge=0)
    drive_current_ma: float = Field(ge=0)
    forward_power_mw: float = Field(ge=0)
    backward_power_mw: float = Field(ge=0)


class TaperedAmplifierParams(CamelModel):
    # --- Existing (kept for back-compat with the bare-chip seed entry) ---
    small_signal_gain_db: float
    saturation_power_mw: float = Field(gt=0)
    min_input_power_mw: float | None = Field(default=10.0, ge=0)
    max_input_power_mw: float | None = None
    input_acceptance_radius_mm: float | None = Field(default=25.0, gt=0)
    ase: TaperedAmplifierAse
    input_spatial_mode_x: GaussianMode | None = None
    input_spatial_mode_y: GaussianMode | None = None
    input_polarization: JonesVector = Field(default_factory=lambda: JonesVector(ey_re=1.0))
    # Forward-looking field: configured for completeness so the structured
    # editor can persist it. Not yet read by ray-tracer / solver — when
    # consumed it should describe the SEED's expected transverse profile
    # (TA chips amplify regardless, but BeamScopePanel can use it for the
    # input-side overlay).
    input_transverse_mode: TransverseMode = Field(default_factory=lambda: TransverseMode())
    output_spatial_mode_x: GaussianMode
    output_spatial_mode_y: GaussianMode
    output_transverse_mode: TransverseMode = Field(default_factory=lambda: TransverseMode())
    # Forward-looking field: stored so the structured editor can persist
    # it. Not yet read by ray-tracer / solver. When consumed it should
    # describe the polarisation of the FORWARD-emitted (output-port) beam,
    # which is typically pinned by the chip's TM gain preference even if
    # the seed has a different state.
    output_polarization: JonesVector = Field(default_factory=lambda: JonesVector(ey_re=1.0))

    # --- New: BoosTA pro–style operating point + bidirectional emission ---
    # Wavelength is the SEED's wavelength normally (TA inherits from input)
    # but we expose it explicitly so the user can configure a stand-alone TA
    # that emits ASE without a seed source.
    center_wavelength_nm: float | None = Field(default=None, gt=0)
    # Drive current — primary control knob in the lab. Default 2400 mA per
    # the BoosTA pro datasheet; clamped to [0, drive_current_max_ma].
    drive_current_ma: float = Field(default=2400.0, ge=0)
    drive_current_max_ma: float = Field(default=5000.0, gt=0)
    # ASE samples (no seed): {current → fwd_power, bwd_power}. Empty list
    # falls back to legacy `ase.power_mw` as forward-only ASE.
    ase_samples: list[TaperedAmplifierAseSample] = Field(default_factory=list)
    # Gain samples (with seed): 2D table of (input, current) → (fwd, bwd).
    # Empty list falls back to legacy small_signal_gain_db / saturation_power
    # for forward-only computation.
    gain_samples: list[TaperedAmplifierGainSample] = Field(default_factory=list)
    # Backward beam profile (the beam that exits the SEED port back toward
    # the master laser / isolator). Optional — when None, ray-tracer mirrors
    # the forward profile so the backward beam at least has the right scale.
    backward_spatial_mode_x: GaussianMode | None = None
    backward_spatial_mode_y: GaussianMode | None = None


# Passive ----------------------------------------------------------------------


class MirrorParams(CamelModel):
    reflectivity: float = Field(default=0.99, ge=0.0, le=1.0)
    surface_quality_nm: float | None = None
    # Time-domain / wave-optics extensions (all optional; missing = ideal):
    clear_aperture_mm: float | None = Field(default=None, gt=0)
    group_delay_ps: float = 0.0

    # V2 Phase 2 (alembic 0028): the reflective-surface normal moved from
    # `surface_normal_body_local` here to
    # ``objects.properties.anchorBindings[kind:opticalSurface].payload.normalBodyLocal``.
    # Inputs that still carry the old field have it silently dropped so V1
    # client uploads keep working — but it is no longer authoritative and
    # nobody reads it anymore.
    @model_validator(mode="before")
    @classmethod
    def _drop_v1_normal_field(cls, data: Any) -> Any:
        if isinstance(data, dict):
            data = dict(data)
            for legacy_key in (
                "surfaceNormalBodyLocal",
                "surface_normal_body_local",
                "normalLocal",
                "normal_local",
            ):
                data.pop(legacy_key, None)
        return data


class LensSphericalParams(CamelModel):
    focal_mm: float
    numerical_aperture: float | None = None
    transmission: float = Field(default=0.99, ge=0.0, le=1.0)
    clear_aperture_mm: float | None = Field(default=None, gt=0)
    gvd_fs2: float = 0.0
    material: str | None = None  # "BK7", "fused_silica", "ZnSe", ...


class LensCylindricalParams(CamelModel):
    focal_mm: float
    cylindrical_axis: Literal["x", "y"] = "x"
    transmission: float = Field(default=0.99, ge=0.0, le=1.0)
    clear_aperture_mm: float | None = Field(default=None, gt=0)
    gvd_fs2: float = 0.0
    material: str | None = None


class WaveplateParams(CamelModel):
    retardance_lambda: float = Field(default=0.5, gt=0)  # 0.5 = HWP, 0.25 = QWP
    # V2 Phase 4 (alembic 0030): the fast-axis angle moved from
    # `fast_axis_deg_beam_local` here to a polarizationReference binding
    # (role="fast") on the SceneObject. The route layer synthesises the
    # legacy field on read and translates back on write so the existing
    # WaveplateAdjustControls keeps working.
    transmission: float = Field(default=0.99, ge=0.0, le=1.0)
    clear_aperture_mm: float | None = Field(default=None, gt=0)
    group_delay_ps: float = 0.0
    gvd_fs2: float = 0.0

    @model_validator(mode="before")
    @classmethod
    def _drop_v2_tracked_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            data = dict(data)
            for key in (
                "fastAxisDegBeamLocal",
                "fast_axis_deg_beam_local",
                "fastAxisDeg",
                "fast_axis_deg",
            ):
                data.pop(key, None)
        return data


class PolarizerParams(CamelModel):
    # V2 Phase 4 (alembic 0030): transmission-axis angle moved to a
    # polarizationReference binding (role="transmission"); see WaveplateParams
    # for the same pattern.
    extinction_ratio_db: float = Field(default=30.0, ge=0.0)
    transmission: float = Field(default=0.95, ge=0.0, le=1.0)

    @model_validator(mode="before")
    @classmethod
    def _drop_v2_tracked_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            data = dict(data)
            for key in (
                "transmissionAxisDegBeamLocal",
                "transmission_axis_deg_beam_local",
                "transmissionAxisDeg",
                "transmission_axis_deg",
            ):
                data.pop(key, None)
        return data

    @model_validator(mode="before")
    @classmethod
    def _accept_legacy_field_names(cls, data: Any) -> Any:
        return _accept_legacy_keys(data, (
            ("transmissionAxisDeg", "transmissionAxisDegBeamLocal"),
            ("transmission_axis_deg", "transmission_axis_deg_beam_local"),
        ))


class BeamSplitterParams(CamelModel):
    """V2 Phase 6 (alembic 0032): coating normal + PBS transmission axis
    moved to anchor bindings. The remaining knobs are pure transfer
    physics (split ratio, polarising bit, extinction, transmission).
    """

    split_ratio_transmitted: float = Field(default=0.5, ge=0.0, le=1.0)
    polarizing: bool = False
    extinction_ratio_db: float = Field(default=30.0, ge=0.0)
    transmission: float = Field(default=0.99, ge=0.0, le=1.0)

    @model_validator(mode="before")
    @classmethod
    def _drop_v2_tracked_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            data = dict(data)
            for key in (
                "coatingNormalBodyLocal",
                "coating_normal_body_local",
                "coatingNormalLocal",
                "coating_normal_local",
                "transmissionAxisDegBeamLocal",
                "transmission_axis_deg_beam_local",
                "transmissionAxisDeg",
                "transmission_axis_deg",
            ):
                data.pop(key, None)
        return data


class DichroicMirrorParams(CamelModel):
    cutoff_wavelength_nm: float = Field(gt=0)
    pass_band: Literal["short", "long"] = "long"
    transmission: float = Field(default=0.95, ge=0.0, le=1.0)
    reflectivity: float = Field(default=0.95, ge=0.0, le=1.0)


class FiberCouplerParams(CamelModel):
    coupling_efficiency: float = Field(default=0.7, ge=0.0, le=1.0)
    mode_field_diameter_um: float = Field(gt=0)
    fiber_type: Literal["single_mode", "polarization_maintaining", "multi_mode"] = "single_mode"
    # Numerical aperture used by the wave-optics solver to clip the input cone;
    # if None, the solver uses MFD-derived effective NA (≈ λ/(π·MFD/2)).
    numerical_aperture: float | None = Field(default=None, gt=0)


# --- Fiber (full patch-cable / pigtail) -------------------------------------
#
# Distinct from the existing `fiber_coupler` element, which models a single
# free-space ↔ fiber transition (one face). The `fiber` element kind models
# the WHOLE patch cable as a bidirectional, two-ended optical component:
# light entering end A propagates to end B (and vice versa) with explicit
# Marcuse / mode-overlap coupling, Fresnel facet losses, length attenuation,
# and Marcuse curvature loss accumulated along the editable Bezier spline.
# See Phase A spec for full physics; this file only defines the persistence
# / API contract.

class FiberType(str, Enum):
    MULTI_MODE = "multi_mode"
    SINGLE_MODE = "single_mode"
    POLARIZATION_MAINTAINING = "polarization_maintaining"


class FiberConnectorType(str, Enum):
    FC = "FC"
    SC = "SC"
    LC = "LC"
    ST = "ST"
    BARE = "BARE"  # un-connectorised pigtail


class FiberConnectorPolish(str, Enum):
    PC = "PC"          # 0° polish, ~3.4% Fresnel uncoated
    UPC = "UPC"        # ultra-physical, slightly lower R but nominally same model
    APC = "APC"        # 8° polish, back-reflection redirected away from source
    AR = "AR"          # AR-coated face (independent of polish angle)


class FiberAttenuationPoint(CamelModel):
    """One sample on the fiber's wavelength-vs-attenuation curve. The
    solver linearly interpolates between adjacent points and clamps to
    the endpoints outside the sampled range."""
    wavelength_nm: float = Field(gt=0)
    db_per_km: float = Field(ge=0)


class BendLossConstants(CamelModel):
    """Macro-bend loss model parameters (Marcuse 1976 curvature-loss
    formula). Stored on the kind so the solver can integrate
    α_bend(R(s)) along the spline. Defaults match a typical 780 nm
    single-mode silica fiber; users can override per kind."""
    # V-number at the design wavelength (= (2π·a/λ)·sqrt(n_core²−n_clad²))
    v_number: float = Field(gt=0, default=2.0)
    # Core radius (µm) and core/cladding refractive indices.
    core_radius_um: float = Field(gt=0, default=2.2)
    n_core: float = Field(gt=1.0, default=1.4506)
    n_clad: float = Field(gt=1.0, default=1.4500)
    # Critical bend radius (mm) below which the Marcuse formula predicts
    # >0.1 dB/m loss. Used as a UI warning threshold AND as a soft floor
    # in the integral so numerical blow-up is avoided when the user
    # accidentally folds the spline to zero.
    critical_radius_mm: float = Field(gt=0, default=25.0)


class FiberEndSpec(CamelModel):
    """Per-end optical parameters. The two ends of a real patch cable are
    usually identical, but the schema lets them differ (hybrid FC/PC ↔
    FC/APC, SM ↔ MM splice etc.)."""

    # Geometric face
    aperture_diameter_mm: float = Field(gt=0, default=0.125)        # cladding OD = 125 µm
    numerical_aperture: float = Field(gt=0, le=1.0, default=0.13)
    # Field shape (only meaningful for SM / PM; MM leaves null).
    mode_field_diameter_um: float | None = Field(default=None, gt=0)
    core_diameter_um: float = Field(gt=0, default=4.4)
    cladding_diameter_um: float = Field(gt=0, default=125.0)

    # Connector + polish + AR
    connector_type: FiberConnectorType = FiberConnectorType.FC
    polish: FiberConnectorPolish = FiberConnectorPolish.PC
    polish_angle_deg: float = 0.0
    # Multiplier applied to the bare Fresnel reflectance R(θ): 1.0 = no
    # AR, ~0.15 = typical AR coating (residual ~0.5 % from a 3.4 % bare
    # facet), 0.0 = perfect AR. The solver still honours the angular and
    # polarisation dependence of R(θ); this is just a flat factor on top.
    fresnel_residual: float = Field(default=1.0, ge=0.0, le=1.0)

    # Glass index at the design wavelength (used for Fresnel computation).
    glass_index_at_design_lambda: float = Field(gt=1.0, default=1.4506)

    # PM only: angle of the slow optical axis in the connector body
    # frame, with 0° aligned to the FC alignment key. Per-instance
    # rotation (`bodyRollDeg` on SceneObject) adds to this. Null for
    # SM / MM.
    slow_axis_deg_in_body_frame: float | None = None

    # Optical port face position in CONNECTOR body-local mm. The
    # connector is positioned by `applyFiberConnectorTransform` at the
    # spline endpoint with +Y outward; this offset rides along the
    # connector's transform automatically. Defaults to (0, 36.28, 0)
    # = the ferrule tip (housing length 36.28 mm in scene units 0.3628).
    # When the user moves the spline node, the world position of the
    # port = endpointWorld + connectorRotation·(faceOffset).
    face_position_mm_body_local: Vec3Mm | None = None


class FiberParams(CamelModel):
    fiber_type: FiberType = FiberType.SINGLE_MODE
    end_a: FiberEndSpec = Field(default_factory=FiberEndSpec)
    end_b: FiberEndSpec = Field(default_factory=FiberEndSpec)

    # Wavelength range. cutoff is single-mode-only — below it the fiber
    # supports multiple modes regardless of its nominal type.
    cutoff_wavelength_nm: float | None = Field(default=None, gt=0)
    operating_wavelength_range_nm: tuple[float, float] = (770.0, 790.0)
    design_wavelength_nm: float = Field(gt=0, default=780.0)

    # Power
    max_input_power_mw: float = Field(gt=0, default=500.0)

    # Wavelength-dependent attenuation curve (linear interp between points,
    # clamped at endpoints). Solver accepts at least 1 point.
    attenuation_curve: list[FiberAttenuationPoint] = Field(
        default_factory=lambda: [FiberAttenuationPoint(wavelength_nm=780.0, db_per_km=5.0)]
    )

    # Bend loss model
    bend_loss: BendLossConstants = Field(default_factory=BendLossConstants)
    min_bend_radius_mm: float = Field(gt=0, default=25.0)

    # Birefringence (PM/SM)
    birefringence_delta_n: float | None = Field(default=None, ge=0.0)
    pmd_coefficient_ps_per_sqrt_km: float | None = Field(default=None, ge=0.0)
    polarization_extinction_ratio_db: float | None = Field(default=None, ge=0.0)  # PM only

    # Modal dispersion (MM only)
    bandwidth_mhz_km: float | None = Field(default=None, gt=0)

    # Used to seed the SM-fiber's frozen random Jones matrix so the same
    # fiber rotates polarisation the same way across reloads. Null = derive
    # from the SceneObject id at solve time.
    random_jones_seed: int | None = None


class IsolatorParams(CamelModel):
    """V2 Phase 8 (alembic 0034): transmission-axis angle moved to a
    polarizationReference binding (role="transmission") on the SceneObject.
    Reuses the polarizer writer / synthesiser pattern from Phase 4.
    """

    forward_loss_db: float = Field(default=0.5, ge=0.0)
    isolation_db: float = Field(default=40.0, ge=0.0)
    group_delay_ps: float = 0.0

    @model_validator(mode="before")
    @classmethod
    def _drop_v2_tracked_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            data = dict(data)
            for key in (
                "transmissionAxisDegBeamLocal",
                "transmission_axis_deg_beam_local",
                "transmissionAxisDeg",
                "transmission_axis_deg",
            ):
                data.pop(key, None)
        return data


# Active / Nonlinear -----------------------------------------------------------


class AOMParams(CamelModel):
    rf_driver_component_id: uuid.UUID | None = None
    base_efficiency: float = Field(default=0.85, ge=0.0, le=1.0)
    deflection_per_mhz_urad: float = Field(default=200.0, ge=0.0)
    acoustic_velocity_m_per_s: float = Field(default=4200.0, gt=0)
    modulation_bandwidth_mhz: float = Field(default=20.0, gt=0)
    center_freq_mhz: float = Field(default=80.0, gt=0)
    # Time-domain switching dynamics:
    rise_time_ns: float = Field(default=50.0, ge=0.0)
    fall_time_ns: float = Field(default=50.0, ge=0.0)
    gvd_fs2: float = 0.0
    # Bragg-diffraction physics fields used by the ray-tracer
    # (frontend rayTrace.ts AOM branch). Optional with sensible TeO₂
    # defaults so legacy AOM rows that don't carry them still trace.
    #   sin θ_B = λ·f / (2·n·v)
    #   I₁/I₀  = sin²(π·L/(2λ·cosθ_B)·√(2·M₂·P_d/W))
    refractive_index: float | None = Field(default=None, gt=0)
    figure_of_merit_m2: float | None = Field(default=None, ge=0)
    crystal_length_mm: float | None = Field(default=None, ge=0)
    acoustic_beam_width_mm: float | None = Field(default=None, ge=0)
    rf_drive_power_w: float | None = Field(default=None, ge=0)
    rf_power_max_w: float | None = Field(default=None, ge=0)
    # V2 Phase 7 (alembic 0033): the RF / acoustic propagation direction
    # moved from `rf_propagation_direction_body_local` (and the duplicate
    # `acoustic_axis_body_local` that aliased the same vector) to a
    # `rfDirection` anchor binding on the SceneObject. Solver / UI reads
    # come back through the route layer's translator (synthesises the
    # legacy field from the binding); writes go through
    # write_aom_rf_direction_body_local. The field stays here as a
    # silently-dropped V1 input compatibility shim — the validator below
    # discards them so V1 client uploads still parse.
    # Visual/ray-trace Bragg angular rolloff. This is intentionally a
    # forgiving alignment tolerance for interactive scene setup.
    bragg_angular_acceptance_mrad: float | None = Field(default=None, gt=0)
    # User-selected primary output order (−1, 0, or +1). Order 0 means
    # the AOM is treated as RF-off — all power on the transmitted
    # branch, no ±1st spawned. ±1 picks which side of the diffraction
    # plane carries the η-fraction of the incident power.
    diffraction_order: int = Field(default=1, ge=-1, le=1)
    # Max |order| spawned by the ray-tracer for visualization. ±1 alone
    # matches a true Bragg cell (Q >> 1); ±2, ±3, ... use Raman-Nath
    # Bessel J_n²(v) intensities to visualize higher-order diffraction
    # for thinner gratings. The 1% visibility threshold below
    # auto-hides orders that don't carry meaningful power.
    max_diffraction_order: int = Field(default=3, ge=1, le=10)
    # Minimum fraction of incident power for a sideband ray to be drawn.
    # 0th and the selected ±1 always show; everything else is gated by
    # this threshold so weak orders don't clutter the scene.
    sideband_visibility_threshold: float = Field(default=0.01, ge=0.0, le=1.0)
    # Continuous angle (deg) selecting the Bragg-tilt axis in the scene
    # Y-Z plane (perpendicular to the canonical scene+X beam direction).
    #   r = 0°  → tilt axis = scene+Z → fan lies in scene XY (horizontal)
    #   r = 90° → tilt axis = scene+Y → fan lies in scene XZ (vertical)
    # Smooth interpolation between the two; arbitrary directions allowed.
    # The align does a 1-D search of the rotation amount around this
    # axis (does not lock any specific Euler component, but composes a
    # quaternion and converts back to (rxDeg, ryDeg, rzDeg)).
    # Phase 5: renamed from `bragg_tilt_axis_angle_deg` to make the
    # frame explicit — this angle is in lab/scene Z-up frame, NOT body.
    bragg_tilt_axis_deg_lab: float = Field(default=90.0)
    # Optional override for the body-local pivot point used by the Bragg
    # rotation during align. When None, the pivot defaults to the midpoint
    # of the asset's `intercept_in` and `intercept_out` anchors (the
    # acousto-optic interaction point for a symmetric AOM where the crystal
    # sits between the two ports). Override only for asymmetric AOMs whose
    # interaction point is not at the geometric midpoint of the entry/exit
    # apertures. Body-local Z-up mm.
    bragg_interaction_point_mm_body_local: list[float] | None = None

    @model_validator(mode="before")
    @classmethod
    def _drop_v2_tracked_and_accept_legacy(cls, data: Any) -> Any:
        if isinstance(data, dict):
            data = dict(data)
            # V2 Phase 7: silently drop the migrated direction fields.
            for key in (
                "rfPropagationDirectionBodyLocal",
                "rf_propagation_direction_body_local",
                "rfPropagationDirectionLocal",
                "rf_propagation_direction_local",
                "acousticAxisBodyLocal",
                "acoustic_axis_body_local",
                "acousticAxisLocal",
                "acoustic_axis_local",
            ):
                data.pop(key, None)
        # Pre-Phase-5 alias for the lab-frame Bragg tilt axis still applies.
        return _accept_legacy_keys(data, (
            ("braggTiltAxisAngleDeg", "braggTiltAxisDegLab"),
            ("bragg_tilt_axis_angle_deg", "bragg_tilt_axis_deg_lab"),
        ))


class EOMParams(CamelModel):
    rf_driver_component_id: uuid.UUID | None = None
    v_pi_v: float = Field(gt=0)
    modulation_kind: Literal["phase", "amplitude"] = "phase"
    modulation_bandwidth_mhz: float = Field(default=100.0, gt=0)
    insertion_loss_db: float = Field(default=3.0, ge=0.0)
    rise_time_ns: float = Field(default=1.0, ge=0.0)
    gvd_fs2: float = 0.0


class NonlinearCrystalParams(CamelModel):
    process: Literal["SHG", "SFG", "DFG", "OPO"]
    chi2_pm_per_v: float = Field(gt=0)
    length_mm: float = Field(gt=0)
    phase_match_temp_c: float | None = None
    phase_match_angle_deg: float | None = None
    walk_off_urad: float = 0.0
    # Material parameters for time-domain split-step Fourier integration:
    refractive_index: float = Field(default=1.5, gt=0)
    gvd_fs2_per_mm: float = 0.0  # pump GVD; for SHG signal we'd add gvd_signal too
    # Phase mismatch in 1/mm; 0 = perfect QPM (default for ideal crystal).
    delta_k_per_mm: float = 0.0


class SaturableAbsorberParams(CamelModel):
    saturation_intensity_w_per_cm2: float = Field(gt=0)
    modulation_depth: float = Field(default=0.5, ge=0.0, le=1.0)
    non_saturable_loss: float = Field(default=0.05, ge=0.0, le=1.0)
    recovery_time_ps: float = Field(gt=0)


# Sinks ------------------------------------------------------------------------


class DetectorParams(CamelModel):
    responsivity_a_per_w: float = Field(gt=0)
    quantum_efficiency: float = Field(default=0.8, ge=0.0, le=1.0)
    bandwidth_mhz: float = Field(gt=0)
    saturation_power_mw: float = Field(gt=0)


class CameraParams(CamelModel):
    resolution_px: tuple[int, int] = (1024, 1024)
    pixel_size_um: float = Field(gt=0)
    quantum_efficiency: float = Field(default=0.5, ge=0.0, le=1.0)
    well_depth_e: int = Field(default=20000, gt=0)


class SpectrometerParams(CamelModel):
    resolution_pm: float = Field(gt=0)
    wavelength_range_nm: tuple[float, float] = (400.0, 1100.0)


class WavemeterParams(CamelModel):
    precision_mhz: float = Field(gt=0)


class BeamDumpParams(CamelModel):
    absorption: float = Field(default=0.999, ge=0.0, le=1.0)


class RfSourceParams(CamelModel):
    """Phase RF.1 — DDS / synth / arbitrary-waveform RF source.

    Default static knobs; the same values can be overridden per-time-tick
    by a TimingProgram of waveform_kind="arbitrary" (Phase RF.3 plumbing
    reads `frequencyMhz` / `powerDbm` / `phaseDeg` from params samples).
    """

    frequency_mhz: float = Field(default=80.0, ge=0.0)
    power_dbm: float = Field(default=0.0)
    phase_deg: float = Field(default=0.0)
    modulation: Literal["none", "am", "fm", "iq"] = "none"


class HornAntennaParams(CamelModel):
    """Phase RF.7 — radiating microwave horn / antenna.

    A SceneObject of this kind takes the chain output and emits a far-field
    lobe along its body-local +Z (or `polarAxisBodyLocal`). The lobe is
    parameterised, not physically solved — gainDbi sets the peak, and the
    cosine exponent (1=isotropic, 2=dipole, large=narrow horn) shapes the
    falloff. A real palace farfield run can populate `radiationPattern`
    later (sampled over θ/φ).
    """

    frequency_ghz: float = Field(default=9.2, gt=0.0)
    gain_dbi: float = Field(default=12.0)
    beamwidth_3db_deg: float = Field(default=30.0, gt=0.0, le=180.0)
    polar_axis_body_local: list[float] | None = Field(default_factory=lambda: [0.0, 0.0, 1.0])
    cosine_exponent: float = Field(default=8.0, ge=0.0)


# --- Per-kind validator registry --------------------------------------------


KIND_PARAMS_MODELS: dict[str, type[CamelModel]] = {
    "laser_source": LaserSourceParams,
    "tapered_amplifier": TaperedAmplifierParams,
    "mirror": MirrorParams,
    # V2 Phase 5 (alembic 0031): lens_spherical renamed to lens_biconvex; the
    # Pydantic class stays LensSphericalParams as an alias since the field
    # shape is identical (focalMm, transmission, …). lens_plano_convex
    # shares the same shape today; thick-lens templates with surface
    # radius / curvature land in a later phase.
    "lens_biconvex": LensSphericalParams,
    "lens_plano_convex": LensSphericalParams,
    "lens_cylindrical": LensCylindricalParams,
    "waveplate": WaveplateParams,
    "polarizer": PolarizerParams,
    "beam_splitter": BeamSplitterParams,
    "dichroic_mirror": DichroicMirrorParams,
    "fiber_coupler": FiberCouplerParams,
    "fiber": FiberParams,
    "isolator": IsolatorParams,
    "aom": AOMParams,
    "eom": EOMParams,
    "nonlinear_crystal": NonlinearCrystalParams,
    "saturable_absorber": SaturableAbsorberParams,
    "detector": DetectorParams,
    "camera": CameraParams,
    "spectrometer": SpectrometerParams,
    "wavemeter": WavemeterParams,
    "beam_dump": BeamDumpParams,
    "rf_source": RfSourceParams,
    "horn_antenna": HornAntennaParams,
}


def _port(port_id: str, role: PortRole, label: str, kind: str | None = None) -> dict[str, Any]:
    return OpticalPort(port_id=port_id, role=role, label=label, kind=kind).model_dump(by_alias=True)


DEFAULT_PORTS: dict[str, dict[str, list[dict[str, Any]]]] = {
    "laser_source": {
        "input": [],
        "output": [_port("out", "output", "Main", "main")],
    },
    "tapered_amplifier": {
        "input": [_port("seed", "input", "Seed", "seed")],
        "output": [_port("out", "output", "Amplified", "main")],
    },
    "mirror": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Reflected", "reflected")],
    },
    "lens_biconvex": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Refracted", "refracted")],
    },
    "lens_plano_convex": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Refracted", "refracted")],
    },
    "lens_cylindrical": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Refracted", "refracted")],
    },
    "waveplate": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Out", "transmitted")],
    },
    "polarizer": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Out", "transmitted")],
    },
    "beam_splitter": {
        "input": [_port("in_a", "input", "Face A", "main"), _port("in_b", "input", "Face B", "main")],
        "output": [_port("out_t", "output", "Transmitted", "transmitted"), _port("out_r", "output", "Reflected", "reflected")],
    },
    "dichroic_mirror": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out_pass", "output", "Pass", "transmitted"), _port("out_refl", "output", "Reflect", "reflected")],
    },
    "fiber_coupler": {
        "input": [_port("in", "input", "Free space", "main")],
        "output": [_port("out", "output", "Fiber", "fiber")],
    },
    "fiber": {
        "input": [
            _port("a", "bidirectional", "End A", "fiber"),
            _port("b", "bidirectional", "End B", "fiber"),
        ],
        "output": [],
    },
    "isolator": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Out", "transmitted")],
    },
    "aom": {
        "input": [_port("in", "input", "In", "main")],
        "output": [
            _port("0th", "output", "0th order", "undiffracted"),
            _port("+1st", "output", "+1st order", "diffracted_plus"),
            _port("-1st", "output", "-1st order", "diffracted_minus"),
        ],
    },
    "eom": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Modulated", "modulated")],
    },
    "nonlinear_crystal": {
        "input": [_port("signal", "input", "Signal", "main"), _port("pump", "input", "Pump", "pump")],
        "output": [_port("out", "output", "Converted", "converted"), _port("idler", "output", "Idler", "idler")],
    },
    "saturable_absorber": {
        "input": [_port("in", "input", "In", "main")],
        "output": [_port("out", "output", "Out", "transmitted")],
    },
    "detector": {
        "input": [_port("in", "input", "In", "main")],
        "output": [],
    },
    "camera": {
        "input": [_port("in", "input", "In", "main")],
        "output": [],
    },
    "spectrometer": {
        "input": [_port("in", "input", "In", "main")],
        "output": [],
    },
    "wavemeter": {
        "input": [_port("in", "input", "In", "main")],
        "output": [],
    },
    "beam_dump": {
        "input": [_port("in", "input", "In", "main")],
        "output": [],
    },
    "rf_source": {
        "input": [],
        "output": [_port("rf_out", "output", "RF Out", "rf")],
    },
    "horn_antenna": {
        "input": [_port("rf_in", "input", "RF In", "rf")],
        "output": [_port("aperture", "output", "Aperture", "rf")],
    },
}

EMITTER_KINDS: set[str] = {"laser_source", "tapered_amplifier"}


# --- Top-level OpticalElement schemas ---------------------------------------


class OpticalElementBase(CamelModel):
    element_kind: ElementKind
    wavelength_range_nm: tuple[float, float] = (400.0, 1100.0)
    input_ports: list[OpticalPort] = Field(default_factory=list)
    output_ports: list[OpticalPort] = Field(default_factory=list)
    kind_params: JsonDict = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_and_normalize(self) -> "OpticalElementBase":
        validator = KIND_PARAMS_MODELS.get(self.element_kind)
        if validator is None:
            raise ValueError(f"Unknown element_kind: {self.element_kind}")
        validated = validator(**self.kind_params)
        self.kind_params = validated.model_dump(by_alias=True, exclude_none=True)

        if not self.input_ports and not self.output_ports:
            defaults = DEFAULT_PORTS.get(self.element_kind)
            if defaults is not None:
                self.input_ports = [OpticalPort(**p) for p in defaults["input"]]
                self.output_ports = [OpticalPort(**p) for p in defaults["output"]]

        low, high = self.wavelength_range_nm
        if low <= 0 or high <= low:
            raise ValueError("wavelength_range_nm must be (low > 0, high > low).")
        return self


class OpticalElementCreate(OpticalElementBase):
    object_id: uuid.UUID


class OpticalElementUpdate(CamelModel):
    element_kind: ElementKind | None = None
    wavelength_range_nm: tuple[float, float] | None = None
    input_ports: list[OpticalPort] | None = None
    output_ports: list[OpticalPort] | None = None
    kind_params: JsonDict | None = None


class OpticalElementOut(OpticalElementBase):
    id: uuid.UUID
    object_id: uuid.UUID
    created_at: datetime
    updated_at: datetime

    # V2 Phase 3 (alembic 0029): the read-direction must NOT re-run the
    # per-kind validator. After the laser_source cutover, the route layer
    # synthesises legacy laser kindParams from objects.properties.opticalSources
    # so the frontend keeps reading the V1 shape. Re-running LaserSourceParams
    # here would silently strip those synthesised fields and the response
    # would emerge with kindParams = {}.
    @model_validator(mode="after")
    def validate_and_normalize(self) -> "OpticalElementOut":  # type: ignore[override]
        return self


# --- OpticalLink schemas ----------------------------------------------------


class OpticalLinkBase(CamelModel):
    from_object_id: uuid.UUID
    from_port: str
    to_object_id: uuid.UUID
    to_port: str
    free_space_mm: float = Field(default=0.0, ge=0.0)
    properties: JsonDict = Field(default_factory=dict)


class OpticalLinkCreate(OpticalLinkBase):
    pass


class OpticalLinkUpdate(CamelModel):
    from_object_id: uuid.UUID | None = None
    from_port: str | None = None
    to_object_id: uuid.UUID | None = None
    to_port: str | None = None
    free_space_mm: float | None = None
    properties: JsonDict | None = None


class OpticalLinkOut(OpticalLinkBase):
    id: uuid.UUID
    created_at: datetime


# --- BeamSegment schemas (L3 simulation outputs) -----------------------------


class BeamSegmentOut(CamelModel):
    id: uuid.UUID
    simulation_run_id: uuid.UUID | None
    optical_link_id: uuid.UUID
    sequence_t_ms: float | None
    beam_index: int
    spectrum: JsonDict
    spatial_x: JsonDict
    spatial_y: JsonDict
    transverse_mode: JsonDict
    polarization_jones: JsonDict
    power_mw: float
    propagation_axis_local: list[float]
    created_at: datetime


# =============================================================================
# Scene view (visibility L3) schemas
# =============================================================================


SceneViewFilterKind = Literal["all", "any", "leaf"]


class SceneViewBase(CamelModel):
    name: str
    description: str | None = None
    icon: str | None = None
    color: str = "#0f766e"
    filter_kind: SceneViewFilterKind = "leaf"
    filter_expr: JsonDict = Field(default_factory=dict)
    overlay_overrides: JsonDict = Field(default_factory=dict)
    is_default: bool = False
    is_pinned: bool = False
    sort_order: int = 0


class SceneViewCreate(SceneViewBase):
    created_by: str | None = None


class SceneViewUpdate(CamelModel):
    name: str | None = None
    description: str | None = None
    icon: str | None = None
    color: str | None = None
    filter_kind: SceneViewFilterKind | None = None
    filter_expr: JsonDict | None = None
    overlay_overrides: JsonDict | None = None
    is_default: bool | None = None
    is_pinned: bool | None = None
    sort_order: int | None = None


class SceneViewOut(SceneViewBase):
    id: uuid.UUID
    created_by: str | None = None
    created_at: datetime
    updated_at: datetime


# =============================================================================
# Collection (Outliner) schemas
# =============================================================================


class CollectionBase(CamelModel):
    name: str
    parent_id: uuid.UUID | None = None
    color: str = "#0f766e"
    visible: bool = True
    rigid_transform: bool = False
    sort_order: int = 0
    properties: JsonDict = Field(default_factory=dict)


class CollectionCreate(CollectionBase):
    pass


class CollectionUpdate(CamelModel):
    name: str | None = None
    parent_id: uuid.UUID | None = None
    color: str | None = None
    visible: bool | None = None
    rigid_transform: bool | None = None
    sort_order: int | None = None
    properties: JsonDict | None = None


class CollectionOut(CollectionBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class CollectionMemberOut(CamelModel):
    collection_id: uuid.UUID
    object_id: uuid.UUID
    sort_order: int = 0
    added_at: datetime


class CollectionMoveRequest(CamelModel):
    parent_id: uuid.UUID | None = None
    sort_order: int | None = None


class CollectionMembershipRequest(CamelModel):
    sort_order: int = 0


class SceneOut(CamelModel):
    assets: list[Asset3DOut]
    components: list[ComponentOut]
    objects: list[SceneObjectOut]
    connections: list[ConnectionOut]
    assembly_relations: list[AssemblyRelationOut] = Field(default_factory=list)
    beam_paths: list[BeamPathOut]
    device_states: list[DeviceStateOut]
    optical_elements: list[OpticalElementOut] = Field(default_factory=list)
    optical_links: list[OpticalLinkOut] = Field(default_factory=list)
    beam_segments: list[BeamSegmentOut] = Field(default_factory=list)
    scene_views: list[SceneViewOut] = Field(default_factory=list)
    collections: list[CollectionOut] = Field(default_factory=list)
    collection_members: list[CollectionMemberOut] = Field(default_factory=list)
    timing_programs: list["TimingProgramOut"] = Field(default_factory=list)


class WebSocketEvent(CamelModel):
    type: str
    payload: JsonDict


# =============================================================================
# Timing programs (per-component timed action sequence)
# =============================================================================
#
# A TimingProgram is a *per-component* sequence of blocks that says what the
# component is doing at each instant. Hardware capability gates what kind of
# program a component is allowed to have:
#
#   laser_source / tapered_amplifier  →  full timeline (any waveform_kind)
#   aom / eom WITH rf_driver_component_id  →  full timeline (incl. arbitrary)
#   aom / eom WITHOUT rf driver  →  on/off gates only
#   passive elements  →  no TimingProgram
#
# 10 ns is the minimum resolution (SpinCore-style); the API validator rounds
# t_start_ns / t_end_ns to multiples of 10 ns on write.

SpinCoreStartMode = Literal["WAIT", "CONTINUE"]
WaveformKind = Literal["const", "linear_ramp", "arbitrary", "gate_on", "gate_off"]
TIMING_RESOLUTION_NS = 10.0


def _round_to_resolution(value: float) -> float:
    """Snap a time value to the nearest 10 ns (TIMING_RESOLUTION_NS)."""
    return round(value / TIMING_RESOLUTION_NS) * TIMING_RESOLUTION_NS


class TimingBlockBase(CamelModel):
    label: str | None = None
    t_start_ns: float = Field(default=0.0, ge=0.0)
    t_end_ns: float = Field(default=0.0, ge=0.0)
    waveform_kind: WaveformKind = "const"
    params: JsonDict = Field(default_factory=dict)
    sort_order: int = 0

    @model_validator(mode="after")
    def _check_block(self) -> "TimingBlockBase":
        # Snap to 10 ns
        self.t_start_ns = _round_to_resolution(self.t_start_ns)
        self.t_end_ns = _round_to_resolution(self.t_end_ns)
        if self.t_end_ns <= self.t_start_ns:
            raise ValueError(
                f"t_end_ns ({self.t_end_ns}) must be > t_start_ns ({self.t_start_ns}); "
                f"minimum block duration is {TIMING_RESOLUTION_NS} ns."
            )
        # Validate per-waveform params shape
        kind = self.waveform_kind
        if kind == "const":
            if "value" not in self.params:
                # default to 0; allows quick-create of empty const block
                self.params = {**self.params, "value": 0.0}
            if not isinstance(self.params.get("value"), (int, float)):
                raise ValueError("const waveform requires params.value as a number")
        elif kind == "linear_ramp":
            for key in ("start", "end"):
                if not isinstance(self.params.get(key), (int, float)):
                    raise ValueError("linear_ramp waveform requires params.start and params.end as numbers")
        elif kind == "arbitrary":
            samples = self.params.get("samples")
            dt_ns = self.params.get("dt_ns")
            if not isinstance(samples, list) or not samples:
                raise ValueError("arbitrary waveform requires non-empty params.samples list")
            if not isinstance(dt_ns, (int, float)) or dt_ns <= 0:
                raise ValueError("arbitrary waveform requires positive params.dt_ns")
        elif kind in ("gate_on", "gate_off"):
            # No params required.
            pass
        return self


class TimingBlockCreate(TimingBlockBase):
    pass


class TimingBlockUpdate(CamelModel):
    label: str | None = None
    t_start_ns: float | None = None
    t_end_ns: float | None = None
    waveform_kind: WaveformKind | None = None
    params: JsonDict | None = None
    sort_order: int | None = None


class TimingBlockOut(TimingBlockBase):
    id: uuid.UUID
    program_object_id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class TimingProgramBase(CamelModel):
    name: str = "program"
    spin_core_start: SpinCoreStartMode = "WAIT"
    duration_ns: float = Field(default=0.0, ge=0.0)
    properties: JsonDict = Field(default_factory=dict)


class TimingProgramUpsert(TimingProgramBase):
    """Idempotent upsert payload for an object's timing program.

    Includes the desired list of blocks; the route replaces the program's
    block set with this list (delete-and-recreate). For incremental edits
    use the per-block routes.
    """
    blocks: list[TimingBlockCreate] = Field(default_factory=list)


class TimingProgramOut(TimingProgramBase):
    object_id: uuid.UUID
    blocks: list[TimingBlockOut] = Field(default_factory=list)
    created_at: datetime
    updated_at: datetime


# =============================================================================
# V2 baseline schemas (alembic 0027, docs/optical-schema-v2.md §3)
# =============================================================================
#
# These are the additive Pydantic shapes for the V2 target schema. They live
# inside JSONB today (objects.properties.{anchorBindings, opticalSources},
# optical_elements.input_ports / output_ports) and table rows for
# revisions / simulation_runs.
#
# Phase 1 only validates round-trips for these shapes — no per-kind cutover
# yet. That happens kind-by-kind in Phase 2+.


# ---- shared primitives ------------------------------------------------------


class V2Vec3(CamelModel):
    """A 3-component float vector. Frame is implied by the surrounding
    field name (e.g. ``normalBodyLocal``).
    """

    x: float
    y: float
    z: float


# ---- anchor bindings (objects.properties.anchorBindings[]) ------------------


AnchorBindingKind = Literal[
    "emissionReference",
    "opticalPortSurface",
    "opticalSurface",
    "detectorArea",
    "interactionVolume",
    "modeField",
    "polarizationReference",
    "rfDirection",
    "crystalAxis",
    "calibrationPoint",
]

BindingFrame = Literal["anchorLocalXY", "bodyLocal", "lab"]


class V2ApertureCircle(CamelModel):
    shape: Literal["circle"] = "circle"
    r_mm: float


class V2ApertureEllipse(CamelModel):
    shape: Literal["ellipse"] = "ellipse"
    x_mm: float
    y_mm: float


class V2ApertureRectangle(CamelModel):
    shape: Literal["rectangle"] = "rectangle"
    x_mm: float
    y_mm: float


V2Aperture = V2ApertureCircle | V2ApertureEllipse | V2ApertureRectangle


class V2AnchorBinding(CamelModel):
    """One per-instance geometry binding tying an asset anchor to a
    physical surface / port / detector area / interaction volume.

    Payload is intentionally a loose dict in Phase 1 because per-kind
    payload shape is still being decided per kind. Tightening happens in
    Phase 2+ (kind-by-kind).
    """

    id: str
    name: str | None = None
    anchor_id: str
    kind: AnchorBindingKind
    frame: BindingFrame = "anchorLocalXY"
    payload: JsonDict = Field(default_factory=dict)


# ---- optical sources (objects.properties.opticalSources[]) -----------------


class V2Linewidth(CamelModel):
    kind: Literal["delta", "lorentzian", "gaussian", "voigt", "measured"] = "delta"
    fwhm_hz: float | None = None
    gaussian_fwhm_hz: float | None = None
    lorentzian_fwhm_hz: float | None = None


class V2Spectrum(CamelModel):
    center_wavelength_nm: float
    wavelength_reference: Literal["vacuum", "air"] = "vacuum"
    linewidth: V2Linewidth = Field(default_factory=V2Linewidth)


class V2Jones(CamelModel):
    ex_re: float
    ex_im: float
    ey_re: float
    ey_im: float


class V2Polarization(CamelModel):
    basis: Literal["beamLocalXY"] = "beamLocalXY"
    normalization: Literal["unit_jones"] = "unit_jones"
    jones: V2Jones


class V2GaussianAxis(CamelModel):
    waist_radius_um: float


class V2GaussianProfile(CamelModel):
    kind: Literal["elliptical_gaussian"] = "elliptical_gaussian"
    x: V2GaussianAxis
    y: V2GaussianAxis
    hard_aperture: JsonDict | None = None


class V2M2GaussianAxis(CamelModel):
    waist_z_offset_mm: float = 0.0
    m_squared: float = 1.0


class V2M2GaussianPropagation(CamelModel):
    model: Literal["m2_gaussian"] = "m2_gaussian"
    x: V2M2GaussianAxis = Field(default_factory=V2M2GaussianAxis)
    y: V2M2GaussianAxis = Field(default_factory=V2M2GaussianAxis)


class V2SpatialEnvelope(CamelModel):
    transverse_profile: V2GaussianProfile
    propagation: V2M2GaussianPropagation = Field(default_factory=V2M2GaussianPropagation)


class V2TransverseMode(CamelModel):
    family: Literal["HG", "LG", "measured"] = "HG"
    m: int = 0
    n: int = 0
    label: str | None = None


class V2BeamSource(CamelModel):
    """Editable source-truth for one emitted beam. Lives in
    ``objects.properties.opticalSources[].beam``.
    """

    power_mw: float
    spectrum: V2Spectrum
    polarization: V2Polarization
    spatial_envelope: V2SpatialEnvelope
    transverse_mode: V2TransverseMode = Field(default_factory=V2TransverseMode)


class V2OpticalSource(CamelModel):
    """One emitted beam source on a scene object. Multiple sources per
    object are allowed (e.g. a TA chip with both forward and backward
    spontaneous emission).
    """

    id: str
    binding_id: str
    enabled: bool = True
    beam: V2BeamSource


class EmissionVisualOverride(CamelModel):
    """Visualisation-only override for one emitted beam, stored under
    ``SceneObject.properties.emissionVisuals[<key>]``.

    Keys: ``"main"`` for laser_source; ``"forward"`` and ``"backward"``
    for tapered_amplifier. Defaults: render with wavelength-derived colour,
    visible. ``visible=False`` causes the ray-tracer to skip the emission
    entirely so downstream optics also stop reflecting that beam.

    This is purely a presentation hint — physics (power, spectrum,
    polarization) is unaffected.
    """

    color_hex: str | None = Field(default=None, pattern=r"^#[0-9A-Fa-f]{6}$")
    visible: bool = True


# ---- optical ports (optical_elements.{input,output}_ports[]) ---------------


PortRole = Literal["input", "output", "bidirectional"]
BranchKind = Literal[
    "main",
    "incident",
    "reflected",
    "transmitted",
    "signal",
    "seed",
    "amplified",
    "forward",
    "generated",
    "order",
    "sideband",
]
PortSide = Literal[
    "side_A",
    "side_B",
    "input_side",
    "output_side",
    "plane_side",
    "convex_side",
    "concave_surface",
]
PortFace = Literal["face_1", "face_2", "face_3", "face_4", "face_5", "face_6"]


class V2OpticalPort(CamelModel):
    """Inline port endpoint on an OpticalElement. Geometry resolves
    through ``binding_id → anchorBindings[] → assets_3d.anchors[]``.
    """

    id: str
    name: str | None = None
    role: PortRole
    branch_kind: BranchKind | None = None
    side: PortSide | None = None
    face: PortFace | None = None
    binding_id: str


# ---- beam segments (solver output snapshot shape) --------------------------


class V2SpatialAxisState(CamelModel):
    q_real: float
    q_imag: float
    w_at_z_um: float | None = None


class V2BeamState(CamelModel):
    """Per-segment beam snapshot. Stored inside
    ``beam_segments.state_at_start`` / ``state_at_end`` JSONB.
    """

    power_mw: float
    spectrum: V2Spectrum
    polarization: V2Polarization
    spatial_x: V2SpatialAxisState
    spatial_y: V2SpatialAxisState
    transverse_mode: V2TransverseMode = Field(default_factory=V2TransverseMode)


# ---- simulation runs / revisions (V2 table-shaped) -------------------------


# V2 Phase 1 valid set was {completed, running, failed}; alembic 0036
# (multiphysics) added 'queued' (created but not yet dispatched) and
# 'cancelled' (user aborted before completion).
SimulationRunStatus = Literal["queued", "running", "completed", "failed", "cancelled"]

# Multi-physics module discriminator.
#
# Lab (formerly "optics_seq"): the integrated 3D workspace that hosts
# every physical device, ray-traces beams, and surfaces every other
# module's results in-context. Stays under the "optics_seq" id for
# backwards compatibility with existing simulation_runs rows.
#
# optics_cavity: pure optical-cavity simulator (FSR / Finesse / Airy
# transmission / stability) — separate workspace, no 3D scene.
# Phase B: spice. Phase C: em_fem. Phase F+: magnetics_dc.
# optics_fdtd reserved for future Phase D.
SimulationModule = Literal[
    "optics_seq",
    "optics_cavity",
    "optics_crystal",
    "optics_fdtd",
    "spice",
    "em_fem",
    "magnetics_dc",
]

# Where a SolverRunner dispatched this row. See backend/app/solvers/runner.py.
SolverRunnerKind = Literal["inproc", "container", "ssh_workstation"]


class V2SimulationRunBase(CamelModel):
    revision_id: uuid.UUID | None = None
    solver_version: str = "optical-solver-v1"
    status: SimulationRunStatus = "completed"
    scene_hash: str | None = None
    settings: JsonDict = Field(default_factory=dict)
    warnings: list[Any] = Field(default_factory=list)
    finished_at: datetime | None = None
    # Multi-physics columns (alembic 0036). Defaults match the legacy-row
    # backfill so existing optical runs round-trip unchanged.
    module: SimulationModule = "optics_seq"
    runner_kind: SolverRunnerKind = "inproc"
    params: JsonDict = Field(default_factory=dict)
    progress: float | None = None
    error_message: str | None = None
    result_summary: JsonDict | None = None
    result_blob_path: str | None = None


class V2SimulationRunCreate(V2SimulationRunBase):
    pass


class V2SimulationRunOut(V2SimulationRunBase):
    id: uuid.UUID
    started_at: datetime


class MultiphysicsSimulationRunCreate(CamelModel):
    """Payload for ``POST /api/simulation-runs``.

    Module is required (decides which solver to dispatch). runner_kind has
    a sensible default per module (Phase A: optics_seq → inproc) so callers
    that don't care can omit it. ``params`` is module-specific JSON.
    """

    module: SimulationModule
    runner_kind: SolverRunnerKind | None = None  # None = use module default
    params: JsonDict = Field(default_factory=dict)


# ---- Circuits (Phase B.1, alembic 0037) -----------------------------------


class CircuitBase(CamelModel):
    name: str
    netlist: str = ""
    schematic: JsonDict = Field(default_factory=dict)
    scene_object_id: uuid.UUID | None = None


class CircuitCreate(CircuitBase):
    pass


class CircuitUpdate(CamelModel):
    name: str | None = None
    netlist: str | None = None
    schematic: JsonDict | None = None
    scene_object_id: uuid.UUID | None = None


class CircuitOut(CircuitBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


# ---- Meshes + EM problems (Phase C.1, alembic 0038) -----------------------


class MeshBase(CamelModel):
    name: str
    mesh_format: Literal["gmsh", "vtk"] = "gmsh"
    source_asset_3d_id: uuid.UUID | None = None


class MeshOut(MeshBase):
    id: uuid.UUID
    file_path: str
    element_count: int | None = None
    max_size_mm: float | None = None
    file_size_bytes: int = 0
    created_at: datetime


class EmPort(CamelModel):
    """One EM port assignment. ``anchor_binding_id`` references an
    ``anchorBindings[].id`` on the SceneObject (the geometry payload
    tells the solver which surface is the port plane).
    """

    id: str
    name: str
    anchor_binding_id: str | None = None
    impedance_ohm: float = 50.0
    mode: Literal["te", "tm", "tem"] = "tem"


class EmFreqSweep(CamelModel):
    start_ghz: float
    stop_ghz: float
    points: int = 51
    scale: Literal["linear", "log"] = "linear"


class EmBoundaryConditions(CamelModel):
    pec_anchor_binding_ids: list[str] = Field(default_factory=list)
    absorbing_anchor_binding_ids: list[str] = Field(default_factory=list)


class EmProblemBase(CamelModel):
    name: str
    scene_object_id: uuid.UUID | None = None
    mesh_id: uuid.UUID | None = None
    ports: list[EmPort] = Field(default_factory=list)
    boundary_conditions: EmBoundaryConditions = Field(default_factory=EmBoundaryConditions)
    freq_range_ghz: EmFreqSweep | None = None


class EmProblemCreate(EmProblemBase):
    pass


class EmProblemUpdate(CamelModel):
    name: str | None = None
    scene_object_id: uuid.UUID | None = None
    mesh_id: uuid.UUID | None = None
    ports: list[EmPort] | None = None
    boundary_conditions: EmBoundaryConditions | None = None
    freq_range_ghz: EmFreqSweep | None = None


class EmProblemOut(EmProblemBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


# ---- Coils + Magnetics problems (Phase F+, alembic 0039) ------------------


CoilShape = Literal["circular_loop", "solenoid", "polyline"]


class CoilBase(CamelModel):
    name: str
    shape: CoilShape = "circular_loop"
    params: JsonDict = Field(default_factory=dict)
    current_a: float = 1.0
    scene_object_id: uuid.UUID | None = None


class CoilCreate(CoilBase):
    pass


class CoilUpdate(CamelModel):
    name: str | None = None
    shape: CoilShape | None = None
    params: JsonDict | None = None
    current_a: float | None = None
    scene_object_id: uuid.UUID | None = None


class CoilOut(CoilBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class MagneticsEvalRegion(CamelModel):
    center_mm: tuple[float, float, float] = (0.0, 0.0, 0.0)
    size_mm: tuple[float, float, float] = (200.0, 200.0, 200.0)
    grid_dim: tuple[int, int, int] = (24, 24, 24)


class MagneticsProblemBase(CamelModel):
    name: str
    coil_ids: list[uuid.UUID] = Field(default_factory=list)
    eval_region: MagneticsEvalRegion = Field(default_factory=MagneticsEvalRegion)


class MagneticsProblemCreate(MagneticsProblemBase):
    pass


class MagneticsProblemUpdate(CamelModel):
    name: str | None = None
    coil_ids: list[uuid.UUID] | None = None
    eval_region: MagneticsEvalRegion | None = None


class MagneticsProblemOut(MagneticsProblemBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


# ---- PulseBlaster channels (Phase F+, alembic 0040) -----------------------


class PulseBlasterChannelBase(CamelModel):
    channel_index: int
    label: str = ""
    target_component_id: uuid.UUID | None = None
    invert: bool = False
    enabled: bool = True


class PulseBlasterChannelCreate(PulseBlasterChannelBase):
    pass


class PulseBlasterChannelUpdate(CamelModel):
    label: str | None = None
    target_component_id: uuid.UUID | None = None
    invert: bool | None = None
    enabled: bool | None = None


class PulseBlasterChannelOut(PulseBlasterChannelBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class PulseBlasterChannelBulkUpsert(CamelModel):
    """Single-call replace-all for the 24 channels (UI bulk save)."""

    channels: list[PulseBlasterChannelCreate]


# ---- RF chain nodes (Phase RF.2, alembic 0041) ----------------------------


RfNodeKind = Literal[
    "dds",
    "synthesizer",
    "amplifier",
    "attenuator",
    "filter_bandpass",
    "filter_lowpass",
    "filter_highpass",
    "splitter",
    "combiner",
    "mixer",
    "switch",
    "isolator",
    "circulator",
    "coax",
    "device",  # terminal (the AOM/EOM consuming the chain)
]


class RfChainNodeBase(CamelModel):
    terminal_scene_object_id: uuid.UUID
    position_in_chain: int
    node_kind: RfNodeKind
    label: str = ""
    gain_db: float = 0.0
    kind_params: JsonDict = Field(default_factory=dict)
    linked_circuit_id: uuid.UUID | None = None
    linked_em_problem_id: uuid.UUID | None = None


class RfChainNodeCreate(RfChainNodeBase):
    pass


class RfChainNodeUpdate(CamelModel):
    position_in_chain: int | None = None
    node_kind: RfNodeKind | None = None
    label: str | None = None
    gain_db: float | None = None
    kind_params: JsonDict | None = None
    linked_circuit_id: uuid.UUID | None = None
    linked_em_problem_id: uuid.UUID | None = None


class RfChainNodeOut(RfChainNodeBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class RfChainBulkReplace(CamelModel):
    """Replace the entire chain for one terminal device. Convenient for
    the panel's drag-reorder editor."""

    terminal_scene_object_id: uuid.UUID
    nodes: list[RfChainNodeCreate]


class PulseBlasterInstructionOut(CamelModel):
    """One row of the compiled SpinCore opcode stream (Phase PB.4)."""

    index: int
    output_state: int
    opcode: str
    data: int
    length_ns: float
    label: str | None = None


class PulseBlasterCompileOut(CamelModel):
    """Compiled program — instruction stream + a Python spinapi rendering."""

    instructions: list[PulseBlasterInstructionOut]
    python_source: str
    bound_channel_count: int
    total_duration_ns: float


class V2RevisionBase(CamelModel):
    label: str
    description: str | None = None
    snapshot: JsonDict
    scene_hash: str | None = None


class V2RevisionCreate(V2RevisionBase):
    pass


class V2RevisionOut(V2RevisionBase):
    id: uuid.UUID
    created_at: datetime
